### ISSUE TITLE
原来上传一个cli项目也能骗到这么多star

### ISSUE THREAD

**Issue by rwrr-0644** [aiplat/uniapp#20]
顺带提醒uniapp引擎可以更新v3了

**Comment by aiplat** [comment]
眼瞎。

**Comment by aiplat** [comment]
> 顺带提醒uniapp引擎可以更新v3了

眼瞎。

**Comment by aiplat** [comment]
> 顺带提醒uniapp引擎可以更新v3了

黑子，uni-app也是有基于vue-cli的，那你去黑它。天下N多库也是基于vue-cli的，那你渣渣地去黑它们。
